site_name: mbed App

docs_dir: docs

use_directory_urls: true

pages:
- ['index.md', 'Getting Started']
- ['what_is_provisioning.md', 'About', "What's the mbed App?"]
- ['use_cases.md', 'About', 'Example Use Cases']
- ['concepts.md', 'About', 'Concepts']
- ['design_principles.md', 'About', 'Design Principles']
- ['protocol.md', 'About', 'Protocol']
- ['faqs.md', 'FAQs']

